### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by patrickkabwe** [patrickkabwe/dpo-node-sdk#16]
Error initiating payment: TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at p (/Users/user/Documents/dpo-node-sdk/playground/node_modules/@kazion/dpopay-sdk/index.js:1:1279)
    at r (/Users/user/Documents/dpo-node-sdk/playground/node_modules/@kazion/dpopay-sdk/index.js:13:80)
    at d.initiatePayment (/Users/user/Documents/dpo-node-sdk/playground/node_modules/@kazion/dpopay-sdk/index.js:13:926)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async initiatePayment (file:///Users/user/Documents/dpo-node-sdk/playground/index.js:40:20)
undefined

**Comment by patrickkabwe** [comment]
To resolve this issue make sure you are not using localhost or 127.0.0.1 use your domain or ngrok
